### ISSUE TITLE
How to use this cli with an API key?

### ISSUE THREAD

**Issue by andreroggeri** [daily-co/pipecat-cloud#56]
Looking for some way to use the `pcc` cli on my CI, but unsure how I can use the API Key for that.

**Comment by markbackman** [comment]
We recommend using the REST APIs for CI:
https://docs.pipecat.daily.co/rest-reference/endpoint/agent-create

Later this week, we'll be adding new endpoints to manage secrets.

**Comment by andreroggeri** [comment]
Sure, but I would rather use the same commands I use locally than write curl commands in my github actions.

**Comment by markbackman** [comment]
Good news: as of `pipecatcloud` 0.4.1, the CLI supports Personal Access Tokens (PATs), which is exactly what you want for CI.

Upgrade to `pipecatcloud>=0.4.2` (0.4.2 also auto-resolves your default org, so you don't need to set `PIPECAT_ORG`), generate a PAT, and expose it via `PIPECAT_TOKEN`:

```yaml
- name: Deploy to Pipecat Cloud
  env:
    PIPECAT_TOKEN: \${{ secrets.PIPECAT_TOKEN }}
  run: uv run pcc deploy
```

PATs work with all CLI commands and inherit your org memberships, so you can use the same `pcc` commands in CI that you use locally. Closing this out, but please reopen if you run into issues.
